
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Facu
 */
public class ConversorFrame extends javax.swing.JFrame {

    /**
     * Creates new form ConversorFrame
     */
    public ConversorFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Conversor de temperatura");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Conversor = new javax.swing.JDesktopPane();
        Contenedor1 = new javax.swing.JPanel();
        Titulo_Contenedor = new javax.swing.JPanel();
        Conver_Temp = new javax.swing.JLabel();
        PedirDatos = new javax.swing.JLabel();
        txGrados = new javax.swing.JTextField();
        btConvertir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Conversor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo_Contenedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Conver_Temp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Conver_Temp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Conver_Temp.setText("Conversor de Temperatura");

        javax.swing.GroupLayout Titulo_ContenedorLayout = new javax.swing.GroupLayout(Titulo_Contenedor);
        Titulo_Contenedor.setLayout(Titulo_ContenedorLayout);
        Titulo_ContenedorLayout.setHorizontalGroup(
            Titulo_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Titulo_ContenedorLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(Conver_Temp, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        Titulo_ContenedorLayout.setVerticalGroup(
            Titulo_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Titulo_ContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Conver_Temp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PedirDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PedirDatos.setText("Ingrese temperatura en grados Celsius");

        btConvertir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-aprobar-y-actualizar-48.png"))); // NOI18N
        btConvertir.setText("Convertir");
        btConvertir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btConvertirMouseClicked(evt);
            }
        });
        btConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConvertirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Contenedor1Layout = new javax.swing.GroupLayout(Contenedor1);
        Contenedor1.setLayout(Contenedor1Layout);
        Contenedor1Layout.setHorizontalGroup(
            Contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Contenedor1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Titulo_Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Contenedor1Layout.createSequentialGroup()
                .addGroup(Contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Contenedor1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PedirDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Contenedor1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(txGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Contenedor1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btConvertir)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        Contenedor1Layout.setVerticalGroup(
            Contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Contenedor1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Titulo_Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(PedirDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txGrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        Conversor.add(Contenedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 16, 400, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Conversor, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Conversor, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConvertirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConvertirActionPerformed

    private void btConvertirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConvertirMouseClicked


        try {
                if (txGrados.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Ingrese un valor a convertir...","Entrada Inválida",JOptionPane.WARNING_MESSAGE);
            }else{

                double celsius = Double.parseDouble(txGrados.getText());
                double farenheit=celsius * 9 / 5 + 32;  
                JOptionPane.showMessageDialog(null, "La Temperatura en grados farenheit es: "+farenheit,"Resultado de la Operación de Conversión",JOptionPane.INFORMATION_MESSAGE);
        }
            
        } catch (Exception NumberFormatException) {
            //Si el usuario ingresa un texto en lugar de un número, capturamos el error e informamos:
            
            JOptionPane.showMessageDialog(null, "Ingrese un valor válido..","Atención",JOptionPane.WARNING_MESSAGE);
            txGrados.setText("");
        }
        
 
    }//GEN-LAST:event_btConvertirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor1;
    private javax.swing.JLabel Conver_Temp;
    private javax.swing.JDesktopPane Conversor;
    private javax.swing.JLabel PedirDatos;
    private javax.swing.JPanel Titulo_Contenedor;
    private javax.swing.JButton btConvertir;
    private javax.swing.JTextField txGrados;
    // End of variables declaration//GEN-END:variables
}
